### PR TITLE
Clean tests

### PR DESCRIPTION
**Pull request by tmodoux**

### CODE REVIEW

**Comment by kebetsi** [comment]
you removed `accesses`, that's not cleaning

**Comment by kschiess** [comment]
Guys, what's the status here? What are our next steps?

**Comment by kebetsi** [comment]
@kschiess Tests weren't passing because `accesses` have a field called `lastUsed` which doesn't match. The fix proposed by @tmodoux just ignored the accesses fields, which is not the way I see it.
So either we drop this issue, or it should be corrected in a better way. I don't really have time for this at the moment. @tmodoux, what do you think?

**Comment by tmodoux** [comment]
Ok I modified the tests so that they also check the accesses. For the lastUsed of the access we are using for the test, I just check that the time approximately match the start of the test (nearest second).

**Comment by kschiess** [comment]
What are our next steps? Should we merge this? Please create a Trello card for this work, so we can prioritise.

**Review by kebetsi — APPROVED** [review]
OK

**Pull request merged**
